import { useState } from "react";

interface PricingFeature {
  text: string;
}

interface PricingPlan {
  name: string;
  monthlyPrice: string;
  annualPrice: string;
  annualTotal: string;
  period?: string;
  description: string;
  features: PricingFeature[];
  cta: string;
  tier?: "pro" | "business";
  ctaHref?: string;
  highlighted: boolean;
}

const PLANS: PricingPlan[] = [
  {
    name: "Free",
    monthlyPrice: "$0",
    annualPrice: "$0",
    annualTotal: "$0/yr",
    description: "Get started with AI-powered development tools.",
    features: [
      { text: "50 AI requests/day" },
      { text: "10 MCP tools" },
      { text: "Community support" },
      { text: "Basic dashboard" },
    ],
    cta: "Get Started Free",
    ctaHref: "/tools",
    highlighted: false,
  },
  {
    name: "Pro",
    monthlyPrice: "$29",
    annualPrice: "$23",
    annualTotal: "$276/yr",
    period: "/mo",
    description: "Unlock professional tools and higher limits.",
    features: [
      { text: "500 AI requests/day" },
      { text: "All 80+ MCP tools" },
      { text: "Priority support" },
      { text: "API key vault (BYOK)" },
      { text: "Advanced analytics" },
    ],
    cta: "Upgrade to Pro",
    tier: "pro",
    highlighted: true,
  },
  {
    name: "Business",
    monthlyPrice: "$99",
    annualPrice: "$79",
    annualTotal: "$948/yr",
    period: "/mo",
    description: "Unlimited access and dedicated support for teams.",
    features: [
      { text: "Unlimited AI requests" },
      { text: "All 80+ MCP tools" },
      { text: "Dedicated support" },
      { text: "Team management" },
      { text: "Custom integrations" },
      { text: "Marketplace revenue share" },
    ],
    cta: "Upgrade to Business",
    tier: "business",
    highlighted: false,
  },
];

const FAQ_ITEMS = [
  {
    question: "What's included in the free plan?",
    answer:
      "The free plan gives you 50 AI requests per day, access to 10 MCP tools, a basic dashboard, and community support. It's a great way to explore the platform before committing to a paid plan.",
  },
  {
    question: "How do AI requests work?",
    answer:
      "Each time you use a tool (like generating an image, reviewing code, or asking a question), it counts as one AI request. Your daily limit resets at midnight UTC. Unused requests don't carry over to the next day.",
  },
  {
    question: "Can I bring my own API keys?",
    answer:
      "Yes — Pro and Business plans include the API key vault (BYOK). You can add your own OpenAI, Anthropic, or other provider keys and have them used automatically, which can reduce per-request costs.",
  },
  {
    question: "What MCP tools are available?",
    answer:
      "The platform currently offers 80+ MCP tools covering code generation, image processing, data analysis, browser automation, and more. Free users can access 10 core tools; Pro and Business users get all 80+.",
  },
  {
    question: "How does the marketplace revenue share work?",
    answer:
      "Business subscribers who publish tools or integrations to the spike.land marketplace receive a percentage of revenue generated by their tools. Details are set out in the marketplace agreement at sign-up.",
  },
  {
    question: "Is there a refund policy?",
    answer:
      "Yes. If you're not satisfied within the first 14 days of a paid plan, contact us for a full refund. After that, you can cancel anytime and your plan stays active until the end of the billing period.",
  },
  {
    question: "Can I cancel anytime?",
    answer:
      "Yes. You can cancel your subscription at any time from the billing settings page. Your plan stays active until the end of the current billing period, after which you revert to the free tier.",
  },
];

async function handleCheckout(tier: "pro" | "business", annual: boolean) {
  const lookupKey = annual ? `${tier}_annual` : `${tier}_monthly`;
  const res = await fetch("/api/checkout", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ tier, lookup_key: lookupKey }),
  });
  if (!res.ok) {
    const err = (await res.json()) as { error?: string };
    alert(err.error ?? "Checkout failed");
    return;
  }
  const data = (await res.json()) as { url: string };
  window.location.href = data.url;
}

function PlanCard({ plan, annual }: { plan: PricingPlan; annual: boolean }) {
  const isFree = plan.name === "Free";
  const displayPrice = annual ? plan.annualPrice : plan.monthlyPrice;

  const buttonClass = `mt-8 block w-full rounded-lg px-6 py-2.5 text-center text-sm font-semibold transition ${
    plan.highlighted
      ? "bg-primary text-primary-foreground hover:bg-primary/90"
      : isFree
        ? "border border-border text-muted-foreground hover:bg-muted/50"
        : "bg-muted text-foreground hover:bg-muted/80"
  }`;

  return (
    <div
      className={`flex flex-col rounded-2xl border p-6 shadow-sm ${
        plan.highlighted
          ? "border-primary bg-primary/5 ring-2 ring-primary"
          : "border-border bg-card"
      }`}
    >
      {plan.highlighted && (
        <span className="mb-4 self-start rounded-full bg-primary px-3 py-0.5 text-xs font-semibold text-primary-foreground">
          Most Popular
        </span>
      )}

      <h2 className="text-xl font-bold text-foreground">{plan.name}</h2>
      <p className="mt-1 text-sm text-muted-foreground">{plan.description}</p>

      <div className="mt-4">
        <span className="text-3xl font-extrabold text-foreground">{displayPrice}</span>
        {plan.period && <span className="text-base text-muted-foreground">{plan.period}</span>}
        {annual && !isFree && (
          <p className="mt-0.5 text-xs text-muted-foreground">{plan.annualTotal} billed annually</p>
        )}
      </div>

      {annual && !isFree && (
        <span className="mt-2 self-start rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-semibold text-green-700 dark:bg-green-900/30 dark:text-green-400">
          Save 20%
        </span>
      )}

      <ul className="mt-6 flex-1 space-y-2">
        {plan.features.map((f) => (
          <li key={f.text} className="flex items-start gap-2 text-sm text-foreground">
            <svg
              className="mt-0.5 h-4 w-4 shrink-0 text-primary"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            {f.text}
          </li>
        ))}
      </ul>

      {plan.tier ? (
        <button
          type="button"
          onClick={() => handleCheckout(plan.tier!, annual)}
          className={buttonClass}
        >
          {plan.cta}
        </button>
      ) : (
        <a href={plan.ctaHref} className={buttonClass}>
          {plan.cta}
        </a>
      )}
    </div>
  );
}

function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-border py-4">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="flex w-full items-start justify-between text-left gap-4"
        aria-expanded={open}
      >
        <span className="text-sm font-semibold text-foreground">{question}</span>
        <svg
          className={`mt-0.5 h-4 w-4 shrink-0 text-muted-foreground transition-transform ${open ? "rotate-180" : ""}`}
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {open && (
        <p className="mt-3 text-sm text-muted-foreground leading-relaxed">{answer}</p>
      )}
    </div>
  );
}

export function PricingPage() {
  const [annual, setAnnual] = useState(false);

  return (
    <div className="mx-auto max-w-5xl space-y-12 px-4 py-10">
      <div className="text-center space-y-3">
        <h1 className="text-3xl font-bold text-foreground">Simple, Transparent Pricing</h1>
        <p className="text-muted-foreground max-w-xl mx-auto">
          Choose the plan that fits your workflow. All plans include access to the core platform.
        </p>

        {/* Billing toggle */}
        <div
          role="radiogroup"
          aria-label="Billing frequency"
          className="mt-6 inline-flex items-center gap-3 rounded-full border border-border bg-muted p-1"
        >
          <button
            type="button"
            role="radio"
            aria-checked={!annual}
            onClick={() => setAnnual(false)}
            className={`rounded-full px-4 py-1.5 text-sm font-medium transition ${
              !annual ? "bg-background text-foreground shadow-sm" : "text-muted-foreground"
            }`}
          >
            Monthly
          </button>
          <button
            type="button"
            role="radio"
            aria-checked={annual}
            onClick={() => setAnnual(true)}
            className={`rounded-full px-4 py-1.5 text-sm font-medium transition ${
              annual ? "bg-background text-foreground shadow-sm" : "text-muted-foreground"
            }`}
          >
            Annual
            <span className="ml-1.5 rounded-full bg-green-100 px-1.5 py-0.5 text-xs font-semibold text-green-700 dark:bg-green-900/30 dark:text-green-400">
              -20%
            </span>
          </button>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {PLANS.map((plan) => (
          <PlanCard key={plan.name} plan={plan} annual={annual} />
        ))}
      </div>

      <div className="mx-auto max-w-lg text-center rounded-2xl border border-border bg-card p-8 space-y-4">
        <h2 className="text-xl font-bold text-foreground">Need more?</h2>
        <p className="text-sm text-muted-foreground">
          Looking for SSO, custom integrations, SLA guarantees, or dedicated support?
          Let's talk about an Enterprise plan.
        </p>
        <a
          href="mailto:enterprise@spike.land"
          className="inline-block rounded-lg bg-primary px-6 py-2.5 text-sm font-semibold text-primary-foreground hover:bg-primary/90 transition-colors"
        >
          Contact Sales
        </a>
      </div>

      <p className="text-center text-sm text-muted-foreground">
        Pricing and limits are subject to change.
      </p>

      {/* FAQ */}
      <div className="mx-auto max-w-2xl">
        <h2 className="mb-6 text-center text-2xl font-bold text-foreground">
          Frequently Asked Questions
        </h2>
        <div>
          {FAQ_ITEMS.map((item) => (
            <FaqItem key={item.question} question={item.question} answer={item.answer} />
          ))}
        </div>
      </div>
    </div>
  );
}
