import { importMap } from "@spike-land-ai/code";
import { handleApiRequest } from "./apiHandler";
import type Env from "../core-logic/env";
import { handleCORS } from "../core-logic/utils";

const ESM_CDN = "https://esm.sh";

/** Redirect with CORS headers so cross-origin module imports can follow the redirect. */
function corsRedirect(target: string, requestUrl: string): Response {
  const origin = new URL(requestUrl).origin;

  return new Response(null, {
    status: 302,
    headers: {
      Location: target,
      "Access-Control-Allow-Origin": origin || "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
export async function handleFetchApi(
  path: string[],
  request: Request,
  env: Env,
  _ctx: ExecutionContext,
): Promise<Response> {
  if (request.method === "OPTIONS") {
    return handleCORS(request);
  }
  if (path.length === 0 || path[0] === "") {
    const html = "<html><body>Default HTML response</body></html>";
    return new Response(html, {
      status: 200,
      headers: { "Content-Type": "text/html;charset=UTF-8" },
    });
  }

  const handlers: Record<string, () => Promise<Response>> = {
    ping: async () => handlePing(),
    websocket: async () => handleWebSocket(request),
    node_modules: async () => handleUnpkg(path),

    "importMap.json": async () => handleImportMapJson(),

    // REST API: /api/{codeSpace}/{action}
    // This provides cleaner URLs than /api/room/{codeSpace}/{action}
    "api-v1": async () => handleRestApiRequest(path.slice(1), request, env),
    "robots.txt": async () => {
      const cont = `
User-agent: *
Allow: /
Disallow: /private/
Disallow: /admin/
Disallow: /cgi-bin/

# Block access to specific file types
Disallow: /*.pdf$
Disallow: /*.doc$
Disallow: /*.docx$

# Allow search engine crawlers
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

# Sitemap
Sitemap: ${new URL(request.url).origin}/sitemap.xml
      `;
      return new Response(cont, {
        headers: {
          "Content-Type": "text/plain;charset=UTF-8",
          "Cache-Control": "no-cache",
          "Content-Encoding": "gzip",
        },
      });
    },
    api: async () => handleApiRequest(path.slice(1), request, env),
    ata: async () => handleApiRequest(path.slice(1), request, env),
    ipns: async () => handleIpfsRequest(request),
    ipfs: async () => handleIpfsRequest(request),
    live: async () => handleLiveRequest(path, request, env),
  };

  // Serve manifest.webmanifest inline (referenced by index.html)
  if (path.join("/") === "assets/manifest.webmanifest") {
    return new Response(
      JSON.stringify({
        name: "spike.land",
        description: "A platform for spiking, streaming, and sharing content",
        background_color: "#fff",
        theme_color: "#4285f4",
        display: "standalone",
        orientation: "portrait",
        scope: "/",
        start_url: "/",
        lang: "en-US",
        icons: [
          {
            src: "/assets/favicons/android-chrome-192x192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "/assets/favicons/android-chrome-512x512.png",
            sizes: "512x512",
            type: "image/png",
          },
        ],
      }),
      {
        headers: {
          "Content-Type": "application/manifest+json",
          "Cache-Control": "public, max-age=86400",
        },
      },
    );
  }

  const firstPath = path[0];
  if (!firstPath) {
    return redirectToEsmCdn(request);
  }

  // Redirect tailwindcss@<version> to esm.sh with /index.css appended.
  // @tailwindcss/browser resolves @import "tailwindcss" to this URL, expecting CSS,
  // but esm.sh returns a JS module for bare package URLs. Tailwind v4's CSS entry
  // is at index.css (package.json "style" export).
  if (/^tailwindcss@[\d.]+$/.test(firstPath) && path.length === 1) {
    return corsRedirect(`${ESM_CDN}/${firstPath}/index.css`, request.url);
  }

  // Redirect node@<version>/<module>.mjs polyfill URLs to esm.sh bare module paths.
  // These references were generated by the old esm-worker proxy; redirect for
  // backwards compatibility with any cached or in-flight code.
  if (/^node@[\d.]+$/.test(firstPath)) {
    const modulePath = path
      .slice(1)
      .join("/")
      .replace(/\.mjs$/, "");
    return corsRedirect(`${ESM_CDN}/${modulePath}`, request.url);
  }

  const handler = handlers[firstPath];
  return handler ? handler() : redirectToEsmCdn(request);
}

/**
 * Redirect unhandled requests to esm.sh CDN.
 * This replaces the old ESM proxy that cached modules in R2 via esm-worker.
 * Using a 302 redirect lets the browser cache directly from esm.sh.
 */
function redirectToEsmCdn(request: Request): Response {
  const url = new URL(request.url);
  return corsRedirect(`${ESM_CDN}${url.pathname}${url.search}`, request.url);
}

function handlePing(): Response {
  return new Response("ping" + Math.random(), {
    headers: {
      "Content-Type": "text/html;charset=UTF-8",
      "Content-Encoding": "gzip",
      "Cache-Control": "no-cache",
    },
  });
}

function handleWebSocket(request: Request): Response {
  if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
    return new Response("expected websocket", {
      status: 400,
      headers: { "Content-Type": "text/plain" },
    });
  }

  // In Cloudflare Workers: pair[0] goes in the Response (client-facing),
  // pair[1] is the server-side socket that you accept() and communicate through.
  const { 0: serverSocket, 1: clientSocket } = new WebSocketPair();
  clientSocket.accept();

  const response = new Response(null, {
    status: 200,
    headers: { Upgrade: "websocket", Connection: "Upgrade" },
  });
  Object.defineProperty(response, "webSocket", {
    value: serverSocket,
    writable: false,
    enumerable: true,
    configurable: true,
  });
  Object.defineProperty(response, "status", {
    value: 101,
    writable: false,
    enumerable: true,
    configurable: true,
  });
  return response;
}

const handleUnpkg = (path: string[]): Promise<Response> => fetch(path.join("/"));

function handleImportMapJson(): Response {
  return new Response(JSON.stringify(importMap), {
    headers: {
      "Content-Type": "application/json;charset=UTF-8",
      "Cache-Control": "no-cache",
      "Content-Encoding": "gzip",
    },
  });
}

async function handleIpfsRequest(request: Request): Promise<Response> {
  const pathname = new URL(request.url).pathname;

  // Try cloudflare-ipfs.com first, fall back to ipfs.io on non-ok response
  try {
    const primaryUrl = new URL(pathname, "https://cloudflare-ipfs.com").toString();
    const resp = await fetch(primaryUrl);
    if (resp.ok) {
      return resp;
    }
  } catch (_err) {
    // Ignore error and fall back to ipfs.io
  }

  const fallbackUrl = new URL(pathname, "https://ipfs.io").toString();
  return fetch(fallbackUrl);
}

async function handleLiveRequest(path: string[], request: Request, env: Env) {
  const [, codeSpace, ...remainingPath] = path;

  if (!codeSpace) {
    return new Response("Invalid codeSpace", { status: 400 });
  }

  if (remainingPath[0] === "public") {
    return handlePublicRequest(codeSpace, remainingPath.slice(1), request, env);
  }

  if (request.url.endsWith("index.mjs")) {
    return handleLiveIndexRequest(request, env);
  }

  return handleApiRequest(["room", codeSpace, ...remainingPath], request, env).catch(
    (e: Error) =>
      new Response("Error: " + e?.message, {
        status: 500,
        statusText: e?.message,
      }),
  );
}

async function handlePublicRequest(codeSpace: string, path: string[], request: Request, env: Env) {
  const key = `live/${codeSpace}/${path.join("/")}`;

  switch (request.method) {
    case "GET": {
      const object = await env.R2.get(key);
      if (!object) {
        return new Response("File not found", { status: 404 });
      }
      const headers = new Headers();
      object.writeHttpMetadata(headers);
      headers.set("etag", object.httpEtag);
      headers.set("Cache-Control", "public, max-age=14400, stale-while-revalidate=86400");

      const reqOrigin = request.headers.get("Origin") || "";
      headers.set("Access-Control-Allow-Origin", reqOrigin || "*");

      return new Response(object.body, { headers });
    }
    case "PUT":
      if (!request.body) {
        return new Response("Missing request body", { status: 400 });
      }
      await env.R2.put(key, request.body);
      return new Response(`File ${key} uploaded successfully`, { status: 200 });

    case "DELETE":
      await env.R2.delete(key);
      return new Response(`File ${key} deleted successfully`, { status: 200 });

    default:
      return new Response("Method not allowed", { status: 405 });
  }
}

async function handleLiveIndexRequest(request: Request, env: Env) {
  const key = request.url;
  switch (request.method) {
    case "PUT":
      await env.R2.put(key, request.body);
      return new Response(`Put ${key} successfully!`);
    case "DELETE":
      await env.R2.delete(key);
      return new Response(`DEL ${key} successfully!`);
    case "GET": {
      const object = await env.R2.get(key);
      if (!object) {
        const paths = key
          .split("/")
          .slice(-2)
          .map((p) => p.replace(/\.mjs$/, ".js"));
        return handleApiRequest(["room", ...paths], request, env);
      }
      const headers = new Headers();
      object.writeHttpMetadata(headers);
      headers.set("etag", object.httpEtag);
      headers.set("Cache-Control", "public, max-age=31536000");

      const reqOrigin = request.headers.get("Origin") || "";
      headers.set("Access-Control-Allow-Origin", reqOrigin || "*");

      headers.set("Cross-Origin-Embedder-Policy", "require-corp");
      headers.set("Content-Type", "application/javascript; charset=UTF-8");
      return new Response(object.body, { headers });
    }
    default:
      return new Response("Method not allowed", { status: 405 });
  }
}

async function handleRestApiRequest(path: string[], request: Request, env: Env): Promise<Response> {
  // /api-v1/{codeSpace}/{action} -> routes to Durable Object with path /api/{action}
  const [codeSpace, ...remainingPath] = path;

  if (!codeSpace) {
    return new Response(JSON.stringify({ success: false, error: "CodeSpace required in URL" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Handle CORS preflight (unreachable via handleFetchApi which intercepts OPTIONS first,
  // but kept as a safety net if handleRestApiRequest is ever called directly)
  if (request.method === "OPTIONS") {
    const reqOrigin = request.headers.get("Origin") || "";

    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": reqOrigin || "*",
        "Access-Control-Allow-Methods": "GET, PUT, POST, DELETE, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
        "Access-Control-Max-Age": "86400",
      },
    });
  }

  // Get Durable Object for this codeSpace
  let id;
  if (codeSpace.match(/^[0-9a-f]+$/) && codeSpace.length === 16) {
    id = env.CODE.idFromString(codeSpace);
  } else if (codeSpace.length <= 32) {
    id = env.CODE.idFromName(codeSpace);
  } else {
    return new Response(JSON.stringify({ success: false, error: "CodeSpace name too long" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const roomObject = env.CODE.get(id);
  const newUrl = new URL(request.url);
  // Route to /api/{action} inside the Durable Object
  newUrl.pathname = "/api/" + remainingPath.join("/");
  newUrl.searchParams.set("room", codeSpace);

  return roomObject.fetch(new Request(newUrl.toString(), request));
}
