import { useState } from "react";
import { useAuth } from "../hooks/useAuth";
import { useAnalytics } from "../hooks/useAnalytics";
import { usePricing } from "../hooks/usePricing";
import { apiFetch } from "../../core-logic/api";

interface PricingFeature {
  text: string;
}

interface PricingPlan {
  name: string;
  monthlyPrice: string;
  annualPrice: string;
  annualTotal: string;
  period?: string;
  description: string;
  features: PricingFeature[];
  cta: string;
  tier?: "pro" | "business";
  ctaHref?: string;
  highlighted: boolean;
}

function makePlans(pricing: import("../hooks/usePricing").PricingData): PricingPlan[] {
  return [
    {
      name: "Free",
      monthlyPrice: "$0",
      annualPrice: "$0",
      annualTotal: "$0/yr",
      description: "Get started with AI-powered development tools.",
      features: [
        { text: "50 AI requests/day" },
        { text: "10 MCP (Model Context Protocol) tools" },
        { text: "Community support" },
        { text: "Basic dashboard" },
      ],
      cta: "Get Started Free",
      ctaHref: "/apps",
      highlighted: false,
    },
    {
      name: "Pro",
      monthlyPrice: pricing.pro.monthly,
      annualPrice: pricing.pro.annual,
      annualTotal: pricing.pro.annualTotal,
      period: "/mo",
      description: "Unlock professional tools and higher limits.",
      features: [
        { text: "500 AI requests/day" },
        { text: "All 250+ MCP tools" },
        { text: "Priority support" },
        { text: "API key vault — Bring Your Own Keys (BYOK)" },
        { text: "Advanced analytics" },
      ],
      cta: "Upgrade to Pro",
      tier: "pro",
      highlighted: true,
    },
    {
      name: "Business",
      monthlyPrice: pricing.business.monthly,
      annualPrice: pricing.business.annual,
      annualTotal: pricing.business.annualTotal,
      period: "/mo",
      description: "Unlimited access and dedicated support for teams.",
      features: [
        { text: "Unlimited AI requests" },
        { text: "All 250+ MCP tools" },
        { text: "Dedicated support" },
        { text: "Team management" },
        { text: "Custom integrations" },
        { text: "Marketplace revenue share" },
      ],
      cta: "Upgrade to Business",
      tier: "business",
      highlighted: false,
    },
    {
      name: "Enterprise",
      monthlyPrice: "Custom",
      annualPrice: "Custom",
      annualTotal: "",
      description: "SSO, RBAC, and dedicated support for large teams.",
      features: [
        { text: "Everything in Business" },
        { text: "SSO / SAML authentication" },
        { text: "Custom RBAC & permissions" },
        { text: "SLA guarantee (99.9%)" },
        { text: "Dedicated support engineer" },
        { text: "Audit logs & compliance" },
        { text: "Custom integrations" },
      ],
      cta: "Contact Sales",
      ctaHref: "mailto:zoltan.erdos@spike.land",
      highlighted: false,
    },
  ];
}

const FAQ_ITEMS = [
  {
    question: "What can I build? Do I need to code?",
    answer:
      "You can build AI assistants that interact with databases, read web pages, process images, and more. While some familiarity with coding helps (like using our CLI), our pre-built MCP tools mean you don't need to write the integration logic yourself.",
  },
  {
    question: "What's included in the free plan?",
    answer:
      "The free plan gives you 50 AI requests per day, access to 10 MCP tools, a basic dashboard, and community support. It's a great way to explore the platform before committing to a paid plan.",
  },
  {
    question: "How do AI requests work?",
    answer:
      "Each time you use a tool (like generating an image, reviewing code, or asking a question), it counts as one AI request. Your daily limit resets at midnight UTC. Unused requests don't carry over to the next day.",
  },
  {
    question: "Can I bring my own API keys?",
    answer:
      "Yes — Pro and Business plans include the API key vault (BYOK). You can add your own OpenAI, Anthropic, or other provider keys and have them used automatically, which can reduce per-request costs.",
  },
  {
    question: "What MCP tools are available?",
    answer:
      "The platform currently offers 250+ MCP tools covering code generation, image processing, data analysis, browser automation, and more. Free users can access 10 core tools; Pro and Business users get all 250+.",
  },
  {
    question: "How does the marketplace revenue share work?",
    answer:
      "Business subscribers who publish tools or integrations to the spike.land marketplace receive a percentage of revenue generated by their tools. Details are set out in the marketplace agreement at sign-up.",
  },
  {
    question: "What happens when I hit my daily limit?",
    answer:
      "When you reach your daily AI request limit, new requests will be queued and processed at a reduced rate rather than blocked entirely. You'll see a notification in your dashboard. Limits reset at midnight UTC each day. If you consistently hit your limit, consider upgrading to a higher plan for more capacity.",
  },
  {
    question: "Is there a refund policy?",
    answer:
      "Yes. If you're not satisfied within the first 14 days of a paid plan, contact us for a full refund. After that, you can cancel anytime and your plan stays active until the end of the billing period.",
  },
  {
    question: "Can I cancel anytime?",
    answer:
      "Yes. You can cancel your subscription at any time from the billing settings page. Your plan stays active until the end of the current billing period, after which you revert to the free tier.",
  },
];

async function handleCheckout(
  tier: "pro" | "business",
  annual: boolean,
  isAuthenticated: boolean,
  trackEvent: (event: string, data?: Record<string, unknown>) => void,
) {
  if (!isAuthenticated) {
    window.location.href = "/login";
    return;
  }
  trackEvent("checkout_started", { tier, billing: annual ? "annual" : "monthly" });
  const lookupKey = annual ? `${tier}_annual` : `${tier}_monthly`;
  const res = await apiFetch("/checkout", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ tier, lookup_key: lookupKey }),
  });
  if (!res.ok) {
    const err = (await res.json()) as { error?: string };
    alert(err.error ?? "Checkout failed");
    return;
  }
  const data = (await res.json()) as { url: string };
  window.location.href = data.url;
}

function PlanCard({
  plan,
  annual,
  isAuthenticated,
  trackEvent,
}: {
  plan: PricingPlan;
  annual: boolean;
  isAuthenticated: boolean;
  trackEvent: (event: string, data?: Record<string, unknown>) => void;
}) {
  const isFree = plan.name === "Free";
  const displayPrice = annual ? plan.annualPrice : plan.monthlyPrice;
  const planId = `plan-${plan.name.toLowerCase()}`;

  const buttonClass = `mt-8 block w-full rounded-[calc(var(--radius-control)-0.1rem)] border px-6 py-3 text-center text-sm font-semibold transition ${plan.highlighted
    ? "border-transparent bg-foreground text-background hover:bg-foreground/92"
    : isFree
      ? "border-border bg-background text-foreground hover:border-primary/24 hover:text-primary"
      : "border-border bg-secondary text-foreground hover:border-primary/24 hover:bg-secondary/88"
    }`;

  return (
    <div
      aria-labelledby={planId}
      className={`flex h-full flex-col p-6 ${plan.highlighted ? "rubik-panel-strong" : "rubik-panel"}`}
    >
      {plan.highlighted && (
        <span className="rubik-chip rubik-chip-accent mb-4 self-start">
          Most Popular
        </span>
      )}

      <h2 id={planId} className="text-xl font-semibold tracking-[-0.03em] text-foreground">
        {plan.name}
      </h2>
      <p className="mt-2 text-sm leading-7 text-muted-foreground">{plan.description}</p>

      <div className="mt-4">
        <span className="text-3xl font-semibold tracking-[-0.05em] text-foreground">{displayPrice}</span>
        {plan.period && <span className="text-base text-muted-foreground">{plan.period}</span>}
        {annual && !isFree && (
          <p className="mt-1 text-xs uppercase tracking-[0.12em] text-muted-foreground">
            {plan.annualTotal} billed annually
          </p>
        )}
      </div>

      {annual && !isFree && (
        <span className="mt-3 inline-flex self-start rounded-full border border-success/20 bg-success/70 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-success-foreground">
          Save 20%
        </span>
      )}

      <ul className="mt-6 flex-1 space-y-3">
        {plan.features.map((f) => (
          <li key={f.text} className="flex items-start gap-2 text-sm leading-7 text-foreground">
            <svg
              className="mt-0.5 h-4 w-4 shrink-0 text-primary"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M5 13l4 4L19 7"
              />
            </svg>
            {f.text}
          </li>
        ))}
      </ul>

      {plan.tier ? (
        <button
          type="button"
          onClick={() => handleCheckout(plan.tier!, annual, isAuthenticated, trackEvent)}
          className={buttonClass}
        >
          {!isAuthenticated && plan.tier ? "Get Started" : plan.cta}
        </button>
      ) : (
        <a
          href={plan.ctaHref}
          onClick={() => trackEvent("cta_clicked", { plan: plan.name, tier: plan.tier ?? "free" })}
          className={buttonClass}
        >
          {plan.cta}
        </a>
      )}
    </div>
  );
}

function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  const panelId = `faq-${question.slice(0, 20).replace(/\W+/g, "-").toLowerCase()}`;

  return (
    <div className="border-b border-border py-4 last:border-b-0">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="flex w-full items-start justify-between text-left gap-4"
        aria-expanded={open}
        aria-controls={panelId}
      >
        <span className="text-sm font-semibold text-foreground">{question}</span>
        <svg
          className={`mt-0.5 h-4 w-4 shrink-0 text-muted-foreground transition-transform ${open ? "rotate-180" : ""}`}
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {open && (
        <p id={panelId} className="mt-3 text-sm text-muted-foreground leading-relaxed">
          {answer}
        </p>
      )}
    </div>
  );
}

export function PricingPage() {
  const [annual, setAnnual] = useState(false);
  const { isAuthenticated } = useAuth();
  const { trackEvent } = useAnalytics();
  const { pricing } = usePricing();
  const PLANS = makePlans(pricing);

  return (
    <div className="rubik-container rubik-page rubik-stack">
      <section className="rubik-panel-strong space-y-6 p-6 text-center sm:p-8">
        <div className="space-y-4">
          <span className="rubik-eyebrow">
            <span className="h-2 w-2 rounded-full bg-primary" />
            Pricing
          </span>
          <div className="space-y-3">
            <h1 className="text-4xl font-semibold tracking-[-0.06em] text-foreground sm:text-5xl">
              Transparent pricing for shipping MCP-native software.
            </h1>
            <p className="rubik-lede mx-auto">
              Start free, scale into pro workflows, and keep enterprise controls available when
              your product surface becomes infrastructure.
            </p>
          </div>
        </div>

        <div className="inline-flex items-center gap-2 rounded-full border border-success/20 bg-success/70 px-4 py-2 text-sm font-medium text-success-foreground">
          Launch pricing: £1/mo with code <span className="font-mono font-bold">LAUNCH97</span> —
          14-day free trial included
        </div>

        <div
          role="radiogroup"
          aria-label="Billing frequency"
          className="mx-auto inline-flex items-center gap-3 rounded-full border border-border bg-muted p-1"
          onKeyDown={(e) => {
            if (e.key === "ArrowLeft" || e.key === "ArrowUp") {
              e.preventDefault();
              setAnnual(false);
            }
            if (e.key === "ArrowRight" || e.key === "ArrowDown") {
              e.preventDefault();
              setAnnual(true);
            }
          }}
        >
          <button
            type="button"
            role="radio"
            aria-checked={!annual}
            tabIndex={!annual ? 0 : -1}
            onClick={() => setAnnual(false)}
            className={`rounded-full px-4 py-2 text-sm font-medium transition ${!annual ? "bg-background text-foreground shadow-sm" : "text-muted-foreground"
              }`}
          >
            Monthly
          </button>
          <button
            type="button"
            role="radio"
            aria-checked={annual}
            tabIndex={annual ? 0 : -1}
            onClick={() => setAnnual(true)}
            className={`rounded-full px-4 py-2 text-sm font-medium transition ${annual ? "bg-background text-foreground shadow-sm" : "text-muted-foreground"
              }`}
          >
            Annual
            <span className="ml-1.5 rounded-full bg-green-100 px-1.5 py-0.5 text-xs font-semibold text-green-700 dark:bg-green-900/30 dark:text-green-400">
              -20%
            </span>
          </button>
        </div>
      </section>

      <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">
        {PLANS.map((plan) => (
          <PlanCard
            key={plan.name}
            plan={plan}
            annual={annual}
            isAuthenticated={isAuthenticated}
            trackEvent={trackEvent}
          />
        ))}
      </div>

      <p className="text-center text-sm text-muted-foreground">
        Need a custom plan?{" "}
        <a
          href="mailto:zoltan.erdos@spike.land"
          className="text-primary underline hover:text-primary/80"
        >
          Talk to our team
        </a>
      </p>

      <p className="text-center text-sm text-muted-foreground">
        Pricing and limits are subject to change.{" "}
        {pricing.billedInUsd
          ? `Prices shown in ${pricing.currency}. Billed in USD.`
          : "Prices in USD."}{" "}
        VAT may apply.
        <br />
        Students and educators:{" "}
        <a
          href="mailto:zoltan.erdos@spike.land"
          className="text-primary underline hover:text-primary/80"
        >
          Contact us for academic pricing
        </a>
        .
      </p>

      {/* FAQ */}
      <div className="rubik-panel mx-auto max-w-3xl p-6 sm:p-8">
        <h2 className="mb-6 text-center text-2xl font-semibold tracking-[-0.04em] text-foreground">
          Frequently Asked Questions
        </h2>
        <div>
          {FAQ_ITEMS.map((item) => (
            <FaqItem key={item.question} question={item.question} answer={item.answer} />
          ))}
        </div>
      </div>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: FAQ_ITEMS.map((item) => ({
              "@type": "Question",
              name: item.question,
              acceptedAnswer: {
                "@type": "Answer",
                text: item.answer,
              },
            })),
          }),
        }}
      />
    </div>
  );
}
