/**
 * Bash completion script generator.
 */

export function generateBashCompletions(): string {
  return `# spike CLI bash completions
# Generated by spike completions install
_spike_completions() {
  local cur prev words cword
  _init_completion || return

  local subcommands="serve shell auth alias completions registry chat status"
  local global_opts="--verbose --base-url --help --version"

  if [[ \${cword} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${subcommands} \${global_opts}" -- "\${cur}") )
    return
  fi

  case "\${words[1]}" in
    completions)
      COMPREPLY=( $(compgen -W "install uninstall" -- "\${cur}") )
      ;;
    alias)
      COMPREPLY=( $(compgen -W "set remove list" -- "\${cur}") )
      ;;
    auth)
      COMPREPLY=( $(compgen -W "login logout status" -- "\${cur}") )
      ;;
    serve)
      COMPREPLY=( $(compgen -W "--config --server --server-url --namespace-separator --no-prefix --transport --port --api-key" -- "\${cur}") )
      ;;
    shell)
      COMPREPLY=( $(compgen -W "--config" -- "\${cur}") )
      ;;
    chat)
      COMPREPLY=( $(compgen -W "--config --model --max-tokens" -- "\${cur}") )
      ;;
    status)
      COMPREPLY=( $(compgen -W "--config --json" -- "\${cur}") )
      ;;
    registry)
      COMPREPLY=( $(compgen -W "search add" -- "\${cur}") )
      ;;
    *)
      COMPREPLY=( $(compgen -W "\${global_opts}" -- "\${cur}") )
      ;;
  esac
}

complete -F _spike_completions spike
`;
}
