/**
 * Fish completion script generator.
 */

export function generateFishCompletions(): string {
  return `# spike CLI fish completions
# Generated by spike completions install

# Disable file completions by default
complete -c spike -f

# Subcommands
complete -c spike -n "__fish_use_subcommand" -a serve -d "Start MCP multiplexer server"
complete -c spike -n "__fish_use_subcommand" -a shell -d "Interactive MCP tool explorer"
complete -c spike -n "__fish_use_subcommand" -a auth -d "Manage authentication"
complete -c spike -n "__fish_use_subcommand" -a alias -d "Manage command aliases"
complete -c spike -n "__fish_use_subcommand" -a completions -d "Manage shell completions"
complete -c spike -n "__fish_use_subcommand" -a registry -d "Browse MCP server registry"
complete -c spike -n "__fish_use_subcommand" -a chat -d "Interactive Claude chat with MCP tools"
complete -c spike -n "__fish_use_subcommand" -a status -d "Health check for configured MCP servers"

# Global options
complete -c spike -l verbose -d "Enable verbose logging"
complete -c spike -l base-url -d "Base URL for API" -r
complete -c spike -l help -d "Show help"
complete -c spike -l version -d "Show version"

# completions subcommands
complete -c spike -n "__fish_seen_subcommand_from completions" -a install -d "Install shell completions"
complete -c spike -n "__fish_seen_subcommand_from completions" -a uninstall -d "Remove shell completions"

# alias subcommands
complete -c spike -n "__fish_seen_subcommand_from alias" -a set -d "Create an alias"
complete -c spike -n "__fish_seen_subcommand_from alias" -a remove -d "Remove an alias"
complete -c spike -n "__fish_seen_subcommand_from alias" -a list -d "List aliases"

# serve options
complete -c spike -n "__fish_seen_subcommand_from serve" -l config -d "Config file path" -rF
complete -c spike -n "__fish_seen_subcommand_from serve" -l server -d "Add stdio server" -r
complete -c spike -n "__fish_seen_subcommand_from serve" -l server-url -d "Add HTTP/SSE server" -r
complete -c spike -n "__fish_seen_subcommand_from serve" -l transport -d "Transport type" -ra "stdio http sse"
complete -c spike -n "__fish_seen_subcommand_from serve" -l port -d "Port for HTTP/SSE" -r
complete -c spike -n "__fish_seen_subcommand_from serve" -l api-key -d "API key for auth" -r

# auth subcommands
complete -c spike -n "__fish_seen_subcommand_from auth" -a login -d "Log in to spike.land"
complete -c spike -n "__fish_seen_subcommand_from auth" -a logout -d "Log out"
complete -c spike -n "__fish_seen_subcommand_from auth" -a status -d "Show auth status"

# shell options
complete -c spike -n "__fish_seen_subcommand_from shell" -l config -d "Config file path" -rF

# chat options
complete -c spike -n "__fish_seen_subcommand_from chat" -l config -d "Config file path" -rF
complete -c spike -n "__fish_seen_subcommand_from chat" -l model -d "Claude model to use" -r
complete -c spike -n "__fish_seen_subcommand_from chat" -l max-tokens -d "Max response tokens" -r

# status options
complete -c spike -n "__fish_seen_subcommand_from status" -l config -d "Config file path" -rF
complete -c spike -n "__fish_seen_subcommand_from status" -l json -d "Output as JSON"

# registry subcommands
complete -c spike -n "__fish_seen_subcommand_from registry" -a search -d "Search MCP server registry"
complete -c spike -n "__fish_seen_subcommand_from registry" -a add -d "Add server from registry"
`;
}
