/**
 * Zsh completion script generator.
 */

export function generateZshCompletions(): string {
  return `#compdef spike
# spike CLI zsh completions
# Generated by spike completions install

_spike() {
  local -a subcommands global_opts

  subcommands=(
    'serve:Start MCP multiplexer server'
    'shell:Interactive MCP tool explorer'
    'auth:Manage authentication'
    'alias:Manage command aliases'
    'completions:Manage shell completions'
    'registry:Browse MCP server registry'
    'chat:Interactive Claude chat with MCP tools'
    'status:Health check for configured MCP servers'
  )

  global_opts=(
    '--verbose[Enable verbose logging]'
    '--base-url[Base URL for API]:url:'
    '--help[Show help]'
    '--version[Show version]'
  )

  if (( CURRENT == 2 )); then
    _describe 'subcommand' subcommands
    _arguments $global_opts
    return
  fi

  case $words[2] in
    completions)
      local -a comp_cmds
      comp_cmds=('install:Install shell completions' 'uninstall:Remove shell completions')
      _describe 'completions command' comp_cmds
      ;;
    alias)
      local -a alias_cmds
      alias_cmds=('set:Create an alias' 'remove:Remove an alias' 'list:List aliases')
      _describe 'alias command' alias_cmds
      ;;
    serve)
      _arguments \\
        '--config[Config file path]:file:_files' \\
        '--server[Add stdio server]:name=command:' \\
        '--server-url[Add HTTP/SSE server]:name=url:' \\
        '--namespace-separator[Tool name separator]:separator:' \\
        '--no-prefix[Do not namespace tool names]' \\
        '--transport[Transport type]:type:(stdio http sse)' \\
        '--port[Port for HTTP/SSE]:port:' \\
        '--api-key[API key for auth]:key:'
      ;;
    shell)
      _arguments '--config[Config file path]:file:_files'
      ;;
    auth)
      local -a auth_cmds
      auth_cmds=('login:Log in to spike.land' 'logout:Log out' 'status:Show auth status')
      _describe 'auth command' auth_cmds
      ;;
    chat)
      _arguments \\
        '--config[Config file path]:file:_files' \\
        '--model[Claude model to use]:model:' \\
        '--max-tokens[Max response tokens]:tokens:'
      ;;
    status)
      _arguments \\
        '--config[Config file path]:file:_files' \\
        '--json[Output as JSON]'
      ;;
    registry)
      local -a reg_cmds
      reg_cmds=('search:Search MCP server registry' 'add:Add server from registry')
      _describe 'registry command' reg_cmds
      ;;
  esac
}

_spike "$@"
`;
}
