enableGlobalCache: false

enableImmutableInstalls: false

enableTelemetry: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1111867

packageExtensions:
  "@acemir/cssom@*":
    dependencies:
      cssstyle: "*"
  "@better-auth/core@*":
    dependencies:
      "@better-auth/utils": "*"
      "@better-fetch/fetch": "*"
      better-call: "*"
      jose: "*"
      kysely: "*"
      nanostores: "*"
  "@better-auth/drizzle-adapter@*":
    dependencies:
      "@better-auth/core": "*"
      "@better-auth/utils": "*"
  "@prisma/client@*":
    dependencies:
      "@prisma/engines": "*"
  mz@*:
    dependencies:
      graceful-fs: "*"
  vite@*:
    dependencies:
      ms: "*"

pnpMode: loose

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin
    - win32

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.13.0.cjs
