/**
 * Converts Next.js configuration to Vite + Hono equivalents.
 *
 * Transforms:
 *   next.config.js        → vite.config.ts skeleton
 *   NEXT_PUBLIC_* env vars → VITE_* env vars
 *   Rewrites / redirects  → Hono middleware
 */

import type { TransformResult } from "./types.ts";

/** A parsed rewrite or redirect rule. */
interface RouteRule {
  source: string;
  destination: string;
  permanent?: boolean;
  type: "rewrite" | "redirect";
}

/**
 * Convert a next.config.js source to a vite.config.ts skeleton.
 */
export function convertConfig(_filename: string, source: string): TransformResult {
  const warnings: string[] = [];

  const viteConfig = generateViteConfig(source, warnings);

  return {
    filename: "vite.config.ts",
    original: source,
    transformed: viteConfig,
    warnings,
  };
}

/**
 * Generate a vite.config.ts from next.config.js content.
 */
function generateViteConfig(nextConfig: string, warnings: string[]): string {
  const features = detectNextFeatures(nextConfig);

  const imports: string[] = [
    'import { defineConfig } from "vite";',
    'import react from "@vitejs/plugin-react";',
  ];

  const plugins: string[] = ["react()"];
  const configEntries: string[] = [];

  // Handle base path / basePath
  const basePathMatch = nextConfig.match(/basePath\s*:\s*['"]([^'"]+)['"]/);
  if (basePathMatch) {
    configEntries.push(`  base: "${basePathMatch[1]}",`);
  }

  // Handle trailing slash
  if (features.trailingSlash) {
    warnings.push(
      "trailingSlash config detected — Vite does not enforce trailing slashes, handle in router or server",
    );
  }

  // Handle i18n
  if (features.i18n) {
    warnings.push(
      "i18n config detected — must be manually migrated (consider react-i18next or similar)",
    );
  }

  // Handle images / domains
  if (features.images) {
    warnings.push(
      "next/image config (domains, formats) detected — not needed with native <img> tags",
    );
  }

  // Handle webpack customization
  if (features.webpack) {
    warnings.push(
      "Custom webpack config detected — migrate to Vite plugins or vite.config.ts build options",
    );
  }

  // Handle experimental features
  if (features.experimental) {
    warnings.push("Experimental Next.js features detected — review and migrate manually");
  }

  // Handle headers
  if (features.headers) {
    warnings.push(
      "Custom headers detected — migrate to Hono middleware (see generated middleware file)",
    );
  }

  // Handle rewrites/redirects
  if (features.rewrites) {
    warnings.push("Rewrites detected — convert to Hono middleware in routes/rewrites.ts");
  }

  if (features.redirects) {
    warnings.push("Redirects detected — convert to Hono redirect handlers");
  }

  // Handle env vars in the config itself
  const envVars = extractEnvVarNames(nextConfig);
  if (envVars.length > 0) {
    configEntries.push("  // Environment variable mapping:");
    configEntries.push("  // " + envVars.map((v) => `NEXT_PUBLIC_${v} → VITE_${v}`).join(", "));
  }

  // TanStack Router plugin
  imports.push('import { TanStackRouterVite } from "@tanstack/router-plugin/vite";');
  plugins.unshift("TanStackRouterVite()");

  const lines = [
    "// AUTO-GENERATED by nextjs-transform — manual review needed",
    "",
    ...imports,
    "",
    "export default defineConfig({",
    "  plugins: [",
    ...plugins.map((p) => `    ${p},`),
    "  ],",
    "  server: {",
    "    port: 3000,",
    "    proxy: {",
    '      "/api": {',
    '        target: "http://localhost:8787",',
    "        changeOrigin: true,",
    "      },",
    "    },",
    "  },",
    "  build: {",
    '    target: "esnext",',
    '    outDir: "dist",',
    '    minify: "esbuild",',
    "  },",
    "  resolve: {",
    "    alias: {",
    '      "@": "/src",',
    "    },",
    "  },",
    ...configEntries,
    "});",
  ];

  return lines.join("\n");
}

/**
 * Detect which Next.js features are used in the config.
 */
function detectNextFeatures(source: string): Record<string, boolean> {
  return {
    trailingSlash: /trailingSlash\s*:\s*true/.test(source),
    i18n: /i18n\s*:\s*\{/.test(source),
    images: /images\s*:\s*\{/.test(source),
    webpack: /webpack\s*:\s*(?:function|\()/.test(source),
    experimental: /experimental\s*:\s*\{/.test(source),
    headers: /(?:async\s+)?headers\s*\(\s*\)\s*\{/.test(source),
    rewrites: /(?:async\s+)?rewrites\s*\(\s*\)\s*\{/.test(source),
    redirects: /(?:async\s+)?redirects\s*\(\s*\)\s*\{/.test(source),
  };
}

/**
 * Extract NEXT_PUBLIC_* environment variable name suffixes from source code.
 */
function extractEnvVarNames(source: string): string[] {
  const matches = source.match(/NEXT_PUBLIC_(\w+)/g);
  if (!matches) return [];
  return [...new Set(matches.map((m) => m.replace("NEXT_PUBLIC_", "")))];
}

/**
 * Rewrite NEXT_PUBLIC_* environment variable references in any source file
 * to use Vite's import.meta.env.VITE_* pattern.
 */
export function rewriteEnvVars(filename: string, source: string): TransformResult {
  const warnings: string[] = [];
  let transformed = source;

  // process.env.NEXT_PUBLIC_* → import.meta.env.VITE_*
  transformed = transformed.replace(/process\.env\.NEXT_PUBLIC_(\w+)/g, (_match, name: string) => {
    return `import.meta.env.VITE_${name}`;
  });

  // process.env.* (non-NEXT_PUBLIC) — server-only, needs manual migration
  const serverEnvMatches = transformed.match(/process\.env\.(?!NEXT_PUBLIC_)(\w+)/g);
  if (serverEnvMatches) {
    const unique = [...new Set(serverEnvMatches)];
    for (const envRef of unique) {
      warnings.push(
        `Server-only env var "${envRef}" detected — must be provided via Hono context or API endpoint`,
      );
    }
    // Replace with a clear marker
    transformed = transformed.replace(
      /process\.env\.(?!NEXT_PUBLIC_)(\w+)/g,
      (_match, name: string) => {
        return `/* TODO: Manual review needed — server env */ process.env.${name}`;
      },
    );
  }

  return { filename, original: source, transformed, warnings };
}

/**
 * Extract rewrites and redirects from next.config.js and generate
 * Hono middleware code.
 */
export function convertRewritesAndRedirects(nextConfig: string): {
  code: string;
  warnings: string[];
} {
  const warnings: string[] = [];
  const rules: RouteRule[] = [];

  // Extract rewrite rules (best effort regex)
  // Use greedy capture ([\s\S]*) inside the return block to get all rule objects
  const rewriteSection = nextConfig.match(
    /rewrites\s*\(\s*\)\s*\{[\s\S]*?return\s*\[?([\s\S]*)\]?\s*;?\s*\}/,
  );

  if (rewriteSection && rewriteSection[1]) {
    const rewriteRules = extractRules(rewriteSection[1], "rewrite");
    rules.push(...rewriteRules);
  }

  // Extract redirect rules
  const redirectSection = nextConfig.match(
    /redirects\s*\(\s*\)\s*\{[\s\S]*?return\s*\[?([\s\S]*)\]?\s*;?\s*\}/,
  );

  if (redirectSection && redirectSection[1]) {
    const redirectRules = extractRules(redirectSection[1], "redirect");
    rules.push(...redirectRules);
  }

  if (rules.length === 0) {
    return {
      code: "// No rewrites or redirects found in next.config.js",
      warnings,
    };
  }

  // Generate Hono middleware
  const middlewareLines: string[] = [
    "// AUTO-GENERATED by nextjs-transform — manual review needed",
    "// Migrated rewrites and redirects from next.config.js",
    "",
    'import type { MiddlewareHandler } from "hono";',
    "",
    "export const rewritesAndRedirects: MiddlewareHandler = async (c, next) => {",
    "  const path = new URL(c.req.url).pathname;",
    "",
  ];

  for (const rule of rules) {
    const honoPattern = nextPatternToRegex(rule.source);

    if (rule.type === "redirect") {
      const status = rule.permanent ? 308 : 307;
      middlewareLines.push(`  // Redirect: ${rule.source} → ${rule.destination}`);
      middlewareLines.push(`  if (${honoPattern}.test(path)) {`);
      middlewareLines.push(`    return c.redirect("${rule.destination}", ${status});`);
      middlewareLines.push("  }");
      middlewareLines.push("");
    } else {
      middlewareLines.push(`  // Rewrite: ${rule.source} → ${rule.destination}`);
      middlewareLines.push(
        `  // TODO: Manual review needed — Hono rewrites need custom proxy logic`,
      );
      middlewareLines.push(`  if (${honoPattern}.test(path)) {`);
      middlewareLines.push(`    // TODO: Manual review needed — rewrite to: ${rule.destination}`);
      middlewareLines.push("  }");
      middlewareLines.push("");
    }
  }

  middlewareLines.push("  await next();");
  middlewareLines.push("};");

  return { code: middlewareLines.join("\n"), warnings };
}

/**
 * Extract source/destination rules from a config section.
 */
function extractRules(section: string, type: "rewrite" | "redirect"): RouteRule[] {
  const rules: RouteRule[] = [];
  const rulePattern =
    /\{\s*source\s*:\s*['"]([^'"]+)['"]\s*,\s*destination\s*:\s*['"]([^'"]+)['"]\s*(?:,\s*permanent\s*:\s*(true|false))?\s*\}/g;

  let match: RegExpExecArray | null;
  while ((match = rulePattern.exec(section)) !== null) {
    if (match[1] && match[2]) {
      rules.push({
        source: match[1],
        destination: match[2],
        permanent: match[3] === "true",
        type,
      });
    }
  }

  return rules;
}

/**
 * Convert a Next.js route pattern to a regex for matching.
 */
function nextPatternToRegex(pattern: string): string {
  const regex = pattern
    .replace(/\/:(\w+)\*/g, "/.+") // catch-all
    .replace(/\/:(\w+)/g, "/[^/]+") // dynamic segment
    .replace(/\//g, "\\/"); // escape slashes

  return `/${regex}/`;
}
