name = "spike-agent"
main = "../../src/edge-api/spike-agent/api/index.ts"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[durable_objects]
bindings = [
  { name = "AI_AGENT", class_name = "CodeReviewAgent" }
]

[[migrations]]
tag = "v1"
new_classes = ["CodeReviewAgent"]
