name = "spike-status"
main = "../../src/edge-api/status/api/app.ts"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "status.spike.land/*"
zone_name = "spike.land"
