/**
 * /create App Generator MCP Tools (CF Workers)
 *
 * Search, classify, and manage AI-generated React apps from the /create feature.
 *
 * Most operations delegate to the spike.land API for app management
 * (slug-classifier, codespace-health) not available in this worker.
 */

import { z } from "zod";
import type { ToolRegistryAdapter } from "../../lazy-imports/types";
import { freeTool } from "../../lazy-imports/procedures-index.ts";
import { apiRequest, SPIKE_LAND_BASE_URL, textResult } from "../../db-mcp/tool-helpers";
import type { DrizzleDB } from "../../db/db/db-index.ts";

export function registerCreateTools(
  registry: ToolRegistryAdapter,
  userId: string,
  db: DrizzleDB,
): void {
  const t = freeTool(userId, db);

  registry.registerBuilt(
    t
      .tool(
        "create_search_apps",
        "Search published /create apps by title, description, or slug. " +
          "Results are ordered by popularity.",
        {
          query: z
            .string()
            .min(1)
            .describe("Search query to match against app title, description, or slug."),
          limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10)."),
        },
      )
      .meta({ category: "create", tier: "free" })
      .handler(async ({ input }) => {
        const { query, limit = 10 } = input;
        const params = new URLSearchParams();
        params.set("q", query);
        params.set("limit", String(limit));

        try {
          const apps = await apiRequest<
            Array<{
              slug: string;
              title: string;
              description: string;
              codespaceUrl: string;
              viewCount: number;
            }>
          >(`/api/create/search?${params.toString()}`);

          if (!Array.isArray(apps) || apps.length === 0) {
            return textResult(`No apps found matching "${query}".`);
          }

          let text = `**Found ${apps.length} app(s) matching "${query}":**\n\n`;
          for (const app of apps) {
            text += `- **${app.title}** (\`${app.slug}\`)\n`;
            text += `  ${app.description.slice(0, 150)}\n`;
            text += `  Views: ${app.viewCount} | URL: ${app.codespaceUrl}\n\n`;
          }

          return textResult(text);
        } catch (error) {
          const msg = error instanceof Error ? error.message : "Unknown error";
          return textResult(
            `**Error searching apps:** ${msg}\n\n` +
              `You can browse apps directly at ${SPIKE_LAND_BASE_URL}/create`,
          );
        }
      }),
  );

  registry.registerBuilt(
    t
      .tool("create_get_app", "Get full details for a specific /create app by its slug.", {
        slug: z.string().min(1).describe("Unique slug of the created app."),
      })
      .meta({ category: "create", tier: "free" })
      .handler(async ({ input }) => {
        const { slug } = input;

        try {
          const app = await apiRequest<{
            slug: string;
            title: string;
            description: string;
            status: string;
            codespaceId: string;
            codespaceUrl: string;
            viewCount: number;
            generatedAt: string;
            promptUsed: string;
            outgoingLinks: string[];
            generatedBy?: { id: string; name: string | null };
          }>(`/api/create/${encodeURIComponent(slug)}`);

          let text = `**${app.title}**\n\n`;
          text += `**Slug:** ${app.slug}\n`;
          text += `**Status:** ${app.status}\n`;
          text += `**Description:** ${app.description}\n`;
          text += `**Codespace ID:** ${app.codespaceId}\n`;
          text += `**Codespace URL:** ${app.codespaceUrl}\n`;
          text += `**Views:** ${app.viewCount}\n`;
          text += `**Generated:** ${app.generatedAt}\n`;
          if (app.generatedBy) {
            text += `**Generated By:** ${app.generatedBy.name || app.generatedBy.id}\n`;
          }
          text += `**Prompt Used:** ${app.promptUsed.slice(0, 500)}\n`;
          if (app.outgoingLinks && app.outgoingLinks.length > 0) {
            text += `**Links:** ${app.outgoingLinks.join(", ")}\n`;
          }

          return textResult(text);
        } catch (error) {
          const msg = error instanceof Error ? error.message : "Unknown error";
          return textResult(
            `**Error: NOT_FOUND**\nNo app found with slug "${slug}".\nDetail: ${msg}\n**Retryable:** false`,
          );
        }
      }),
  );

  registry.registerBuilt(
    t
      .tool(
        "create_classify_idea",
        "Use this for the public /create flow — classifies your idea, returns category + template suggestion, not a live app. " +
          "Classify an app idea into a URL slug and category. " +
          "Delegates to the spike.land classification API.",
        {
          text: z.string().min(1).max(2000).describe("App idea text to classify."),
        },
      )
      .meta({ category: "create", tier: "free" })
      .handler(async ({ input }) => {
        try {
          const result = await apiRequest<{
            status: string;
            slug: string | null;
            category: string | null;
            reason?: string;
          }>("/api/create/classify", {
            method: "POST",
            body: JSON.stringify({ text: input.text }),
          });

          let output = `**Classification Result**\n\n`;
          output += `**Status:** ${result.status}\n`;
          output += `**Slug:** ${result.slug || "(none)"}\n`;
          output += `**Category:** ${result.category || "(none)"}\n`;
          if (result.reason) {
            output += `**Reason:** ${result.reason}\n`;
          }

          return textResult(output);
        } catch (error) {
          const msg = error instanceof Error ? error.message : "Unknown error";
          return textResult(
            `**Classification unavailable:** ${msg}\n\n` +
              `The slug classifier requires the spike.land API. Try again later.`,
          );
        }
      }),
  );

  registry.registerBuilt(
    t
      .tool(
        "create_check_health",
        "Check if a codespace is healthy (has real, non-default content).",
        {
          codespace_id: z.string().min(1).describe("Codespace ID to check health for."),
        },
      )
      .meta({ category: "create", tier: "free" })
      .handler(async ({ input }) => {
        try {
          const result = await apiRequest<{ healthy: boolean }>(
            `/api/create/health/${encodeURIComponent(input.codespace_id)}`,
          );

          return textResult(
            `**Codespace Health Check**\n\n` +
              `**ID:** ${input.codespace_id}\n` +
              `**Healthy:** ${result.healthy}`,
          );
        } catch (error) {
          const msg = error instanceof Error ? error.message : "Unknown error";
          return textResult(
            `**Health check unavailable:** ${msg}\n\n` +
              `Health checks require the spike.land API.`,
          );
        }
      }),
  );

  registry.registerBuilt(
    t
      .tool("create_list_top_apps", "List the most popular published /create apps by view count.", {
        limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10)."),
      })
      .meta({ category: "create", tier: "free" })
      .handler(async ({ input }) => {
        const { limit = 10 } = input;
        const params = new URLSearchParams();
        params.set("limit", String(limit));
        params.set("sort", "popular");

        try {
          const apps = await apiRequest<
            Array<{
              slug: string;
              title: string;
              description: string;
              codespaceUrl: string;
              viewCount: number;
            }>
          >(`/api/create/list?${params.toString()}`);

          if (!Array.isArray(apps) || apps.length === 0) {
            return textResult("No healthy published apps found.");
          }

          let text = `**Top ${apps.length} App(s) by Views:**\n\n`;
          for (const app of apps) {
            text += `- **${app.title}** (\`${app.slug}\`) -- ${app.viewCount} views\n`;
            text += `  ${app.description.slice(0, 120)}\n`;
            text += `  URL: ${app.codespaceUrl}\n\n`;
          }

          return textResult(text);
        } catch (error) {
          const msg = error instanceof Error ? error.message : "Unknown error";
          return textResult(
            `**Error listing top apps:** ${msg}\n\n` +
              `Browse apps at ${SPIKE_LAND_BASE_URL}/create`,
          );
        }
      }),
  );

  registry.registerBuilt(
    t
      .tool("create_list_recent_apps", "List the most recently generated published /create apps.", {
        limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10)."),
      })
      .meta({ category: "create", tier: "free" })
      .handler(async ({ input }) => {
        const { limit = 10 } = input;
        const params = new URLSearchParams();
        params.set("limit", String(limit));
        params.set("sort", "recent");

        try {
          const apps = await apiRequest<
            Array<{
              slug: string;
              title: string;
              description: string;
              codespaceUrl: string;
              viewCount: number;
              generatedAt: string;
            }>
          >(`/api/create/list?${params.toString()}`);

          if (!Array.isArray(apps) || apps.length === 0) {
            return textResult("No healthy recent apps found.");
          }

          let text = `**${apps.length} Most Recent App(s):**\n\n`;
          for (const app of apps) {
            text += `- **${app.title}** (\`${app.slug}\`)\n`;
            text += `  ${app.description.slice(0, 120)}\n`;
            text += `  Generated: ${app.generatedAt} | Views: ${app.viewCount}\n`;
            text += `  URL: ${app.codespaceUrl}\n\n`;
          }

          return textResult(text);
        } catch (error) {
          const msg = error instanceof Error ? error.message : "Unknown error";
          return textResult(
            `**Error listing recent apps:** ${msg}\n\n` +
              `Browse apps at ${SPIKE_LAND_BASE_URL}/create`,
          );
        }
      }),
  );

  registry.registerBuilt(
    t
      .tool("create_get_app_status", "Quick status check for a /create app.", {
        slug: z.string().min(1).describe("Unique slug of the created app."),
      })
      .meta({ category: "create", tier: "free" })
      .handler(async ({ input }) => {
        const { slug } = input;

        try {
          const app = await apiRequest<{
            slug: string;
            title: string;
            status: string;
            codespaceUrl: string;
          }>(`/api/create/${encodeURIComponent(slug)}/status`);

          return textResult(
            `**App Status**\n\n` +
              `**Title:** ${app.title}\n` +
              `**Slug:** ${app.slug}\n` +
              `**Status:** ${app.status}\n` +
              `**URL:** ${app.codespaceUrl}`,
          );
        } catch (error) {
          const msg = error instanceof Error ? error.message : "Unknown error";
          return textResult(
            `**Error: NOT_FOUND**\nNo app found with slug "${slug}".\nDetail: ${msg}\n**Retryable:** false`,
          );
        }
      }),
  );
}
