import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import * as esbuild from "esbuild";

const ROOT_DIR = path.resolve(__dirname, "..");
const MONACO_PKG_DIR = path.join(ROOT_DIR, "packages/monaco-editor");
const OUT_DIR = path.join(ROOT_DIR, "dist/monaco-editor");
const CACHE_DIR = path.join(ROOT_DIR, ".deploy-cache");
const CACHE_FILE = path.join(CACHE_DIR, "monaco.hash");
const CONFIG_FILE = path.join(ROOT_DIR, "src/spike-app/lib/monaco-env.ts");

function hashString(str: string): string {
  return crypto.createHash("sha256").update(str).digest("hex").slice(0, 8);
}

async function bundleMonaco() {
  if (!fs.existsSync(path.join(MONACO_PKG_DIR, "out/monaco-editor/esm"))) {
    console.log("Building monaco-editor from source...");
    execSync("npm install --legacy-peer-deps", { stdio: "inherit", cwd: MONACO_PKG_DIR });
    execSync("npx tsx ./build/build-monaco-editor.ts", { stdio: "inherit", cwd: MONACO_PKG_DIR });
  }

  console.log("Bundling monaco-editor with esbuild...");
  if (fs.existsSync(OUT_DIR)) {
    fs.rmSync(OUT_DIR, { recursive: true, force: true });
  }

  // Create a custom entry point to only load what we need
  const entryPointSrc = `
  import * as monaco from './vs/editor/editor.api.js';

  // Languages requested: typescript (includes React/JSX), css, json, html, md, mdx
  import './vs/language/typescript/monaco.contribution.js';
  import './vs/language/css/monaco.contribution.js';
  import './vs/language/json/monaco.contribution.js';
  import './vs/language/html/monaco.contribution.js';

  import './vs/basic-languages/markdown/markdown.contribution.js';
  import './vs/basic-languages/mdx/mdx.contribution.js';
  import './vs/basic-languages/typescript/typescript.contribution.js';
  import './vs/basic-languages/javascript/javascript.contribution.js';

  export { monaco };
  `;
  
  const customEntryPath = path.join(MONACO_PKG_DIR, "out/monaco-editor/esm/custom-entry.js");
  fs.writeFileSync(customEntryPath, entryPointSrc);

  const workerEntryPoints = [
    "vs/language/json/json.worker.js",
    "vs/language/css/css.worker.js",
    "vs/language/html/html.worker.js",
    "vs/language/typescript/ts.worker.js",
    "vs/editor/editor.worker.js",
  ].map((entry) => path.join(MONACO_PKG_DIR, "out/monaco-editor/esm", entry));

  const buildResult = await esbuild.build({
    entryPoints: [
      customEntryPath,
      ...workerEntryPoints,
    ],
    bundle: true,
    format: "esm",
    minify: true,
    splitting: true,
    outdir: OUT_DIR,
    metafile: true,
    loader: {
      ".ttf": "file",
    },
  });

  const fileHashes = Object.keys(buildResult.metafile!.outputs).sort().map(file => {
    const content = fs.readFileSync(path.resolve(ROOT_DIR, file));
    return crypto.createHash("sha256").update(content).digest("hex");
  });
  
  const finalHash = hashString(fileHashes.join(""));
  return { finalHash };
}

async function main() {
  if (!fs.existsSync(CACHE_DIR)) {
    fs.mkdirSync(CACHE_DIR, { recursive: true });
  }

  const { finalHash } = await bundleMonaco();
  console.log(`Generated monaco-editor bundle hash: ${finalHash}`);

  let oldHash = "";
  if (fs.existsSync(CACHE_FILE)) {
    oldHash = fs.readFileSync(CACHE_FILE, "utf-8").trim();
  }

  const R2_BUCKET = "spike-app-assets";
  const BUCKET_PREFIX = `monaco/${finalHash}`;
  const BASE_URL = `https://assets.spike.land/${BUCKET_PREFIX}`;

  if (finalHash === oldHash && process.env.FORCE_DEPLOY !== "1") {
    console.log("Hash matches previously deployed version. Skipping upload.");
  } else {
    console.log(`Hash changed (or no cache). Uploading to R2 bucket: ${R2_BUCKET}...`);
    
    try {
      const files = fs.readdirSync(OUT_DIR, { recursive: true }) as string[];
      for (const file of files) {
        const fullPath = path.join(OUT_DIR, file);
        if (fs.statSync(fullPath).isFile()) {
          const key = `${BUCKET_PREFIX}/${file}`;
          console.log(`  Uploading ${key}...`);
          execSync(
            `npx wrangler r2 object put ${R2_BUCKET}/${key} --file="${fullPath}"`,
            { stdio: "inherit", cwd: ROOT_DIR }
          );
        }
      }

      fs.writeFileSync(CACHE_FILE, finalHash);
      console.log("Deployment successful!");
    } catch (error) {
      console.error("Deployment failed:", error);
      process.exit(1);
    }
  }

  console.log(`Writing config to ${CONFIG_FILE}...`);
  fs.writeFileSync(
    CONFIG_FILE,
    `// Auto-generated by scripts/deploy-monaco.ts\nexport const MONACO_BASE_URL = ${JSON.stringify(BASE_URL)};\n`
  );
  console.log("Done!");
}

main().catch(console.error);
