// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  handle: __t.string(),
  userIdentity: __t.identity().name("user_identity"),
  name: __t.string(),
  description: __t.option(__t.string()),
  coverImageId: __t.option(__t.string()).name("cover_image_id"),
  privacy: __t.string(),
  defaultTier: __t.string().name("default_tier"),
  shareToken: __t.option(__t.string()).name("share_token"),
  sortOrder: __t.u32().name("sort_order"),
  pipelineId: __t.option(__t.string()).name("pipeline_id"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
