// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  handle: __t.string(),
  name: __t.string(),
  description: __t.option(__t.string()),
  privacy: __t.string(),
  defaultTier: __t.string(),
  shareToken: __t.option(__t.string()),
  sortOrder: __t.u32(),
  pipelineId: __t.option(__t.string()),
};
