// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  imageId: __t.string().name("image_id"),
  userIdentity: __t.identity().name("user_identity"),
  tier: __t.string(),
  creditsCost: __t.u32().name("credits_cost"),
  status: __t.string(),
  enhancedUrl: __t.option(__t.string()).name("enhanced_url"),
  enhancedR2Key: __t.option(__t.string()).name("enhanced_r_2_key"),
  enhancedWidth: __t.option(__t.u32()).name("enhanced_width"),
  enhancedHeight: __t.option(__t.u32()).name("enhanced_height"),
  enhancedSizeBytes: __t.option(__t.u64()).name("enhanced_size_bytes"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  retryCount: __t.u32().name("retry_count"),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
  processingStartedAt: __t.option(__t.u64()).name("processing_started_at"),
  processingCompletedAt: __t.option(__t.u64()).name("processing_completed_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
