// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  status: __t.option(__t.string()),
  enhancedUrl: __t.option(__t.string()),
  enhancedR2Key: __t.option(__t.string()),
  enhancedWidth: __t.option(__t.u32()),
  enhancedHeight: __t.option(__t.u32()),
  enhancedSizeBytes: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  processingCompletedAt: __t.option(__t.u64()),
};
