// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userIdentity: __t.identity().name("user_identity"),
  jobType: __t.string().name("job_type"),
  tier: __t.string(),
  creditsCost: __t.u32().name("credits_cost"),
  status: __t.string(),
  prompt: __t.string(),
  inputImageUrl: __t.option(__t.string()).name("input_image_url"),
  outputImageUrl: __t.option(__t.string()).name("output_image_url"),
  outputWidth: __t.option(__t.u32()).name("output_width"),
  outputHeight: __t.option(__t.u32()).name("output_height"),
  outputSizeBytes: __t.option(__t.u64()).name("output_size_bytes"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
