// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userIdentity: __t.identity().name("user_identity"),
  name: __t.string(),
  description: __t.option(__t.string()),
  originalUrl: __t.string().name("original_url"),
  originalR2Key: __t.string().name("original_r_2_key"),
  originalWidth: __t.u32().name("original_width"),
  originalHeight: __t.u32().name("original_height"),
  originalSizeBytes: __t.u64().name("original_size_bytes"),
  originalFormat: __t.string().name("original_format"),
  isPublic: __t.bool().name("is_public"),
  viewCount: __t.u64().name("view_count"),
  tags: __t.array(__t.string()),
  shareToken: __t.option(__t.string()).name("share_token"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
