// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.string(),
  description: __t.option(__t.string()),
  originalUrl: __t.string(),
  originalR2Key: __t.string(),
  originalWidth: __t.u32(),
  originalHeight: __t.u32(),
  originalSizeBytes: __t.u64(),
  originalFormat: __t.string(),
  isPublic: __t.bool(),
  tags: __t.array(__t.string()),
};
