// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AlbumCreateReducer from "./album_create_reducer";
import AlbumDeleteReducer from "./album_delete_reducer";
import AlbumImageAddReducer from "./album_image_add_reducer";
import AlbumImageRemoveReducer from "./album_image_remove_reducer";
import AlbumUpdateReducer from "./album_update_reducer";
import ClaimMcpTaskReducer from "./claim_mcp_task_reducer";
import CompleteMcpTaskReducer from "./complete_mcp_task_reducer";
import CreateAppReducer from "./create_app_reducer";
import CreateAppVersionReducer from "./create_app_version_reducer";
import CreatePageReducer from "./create_page_reducer";
import CreatePageBlockReducer from "./create_page_block_reducer";
import CreditsAddReducer from "./credits_add_reducer";
import CreditsConsumeReducer from "./credits_consume_reducer";
import DeleteAppReducer from "./delete_app_reducer";
import DeletePageReducer from "./delete_page_reducer";
import DeletePageBlockReducer from "./delete_page_block_reducer";
import EnhancementJobCreateReducer from "./enhancement_job_create_reducer";
import EnhancementJobUpdateReducer from "./enhancement_job_update_reducer";
import GenerationJobCreateReducer from "./generation_job_create_reducer";
import GenerationJobUpdateReducer from "./generation_job_update_reducer";
import ImageCreateReducer from "./image_create_reducer";
import ImageDeleteReducer from "./image_delete_reducer";
import ImageUpdateReducer from "./image_update_reducer";
import InvokeToolRequestReducer from "./invoke_tool_request_reducer";
import LinkOauthReducer from "./link_oauth_reducer";
import MarkAgentMessageDeliveredReducer from "./mark_agent_message_delivered_reducer";
import MarkDmReadReducer from "./mark_dm_read_reducer";
import PipelineCreateReducer from "./pipeline_create_reducer";
import PipelineDeleteReducer from "./pipeline_delete_reducer";
import PipelineUpdateReducer from "./pipeline_update_reducer";
import RecordHealthCheckReducer from "./record_health_check_reducer";
import RecordPlatformEventReducer from "./record_platform_event_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import RegisterToolReducer from "./register_tool_reducer";
import RegisterUserReducer from "./register_user_reducer";
import ReorderPageBlocksReducer from "./reorder_page_blocks_reducer";
import RestoreAppReducer from "./restore_app_reducer";
import SendAgentMessageReducer from "./send_agent_message_reducer";
import SendAppMessageReducer from "./send_app_message_reducer";
import SendDmReducer from "./send_dm_reducer";
import SubjectCreateReducer from "./subject_create_reducer";
import SubjectDeleteReducer from "./subject_delete_reducer";
import UnregisterAgentReducer from "./unregister_agent_reducer";
import UnregisterToolReducer from "./unregister_tool_reducer";
import UpdateAppReducer from "./update_app_reducer";
import UpdateAppStatusReducer from "./update_app_status_reducer";
import UpdateCodeSessionReducer from "./update_code_session_reducer";
import UpdatePageReducer from "./update_page_reducer";
import UpdatePageBlockReducer from "./update_page_block_reducer";
import UpdateProfileReducer from "./update_profile_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentRow from "./agent_table";
import AgentMessageRow from "./agent_message_table";
import AlbumRow from "./album_table";
import AlbumImageRow from "./album_image_table";
import AppRow from "./app_table";
import AppMessageRow from "./app_message_table";
import AppVersionRow from "./app_version_table";
import CodeSessionRow from "./code_session_table";
import CreditsRow from "./credits_table";
import DirectMessageRow from "./direct_message_table";
import EnhancementJobRow from "./enhancement_job_table";
import GenerationJobRow from "./generation_job_table";
import HealthCheckRow from "./health_check_table";
import ImageRow from "./image_table";
import McpTaskRow from "./mcp_task_table";
import OauthLinkRow from "./oauth_link_table";
import PageRow from "./page_table";
import PageBlockRow from "./page_block_table";
import PipelineRow from "./pipeline_table";
import PlatformEventRow from "./platform_event_table";
import RegisteredToolRow from "./registered_tool_table";
import SubjectRow from "./subject_table";
import ToolUsageRow from "./tool_usage_table";
import UserRow from "./user_table";
import UserToolPreferenceRow from "./user_tool_preference_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agent: __table({
    name: 'agent',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'agent_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AgentRow),
  agent_message: __table({
    name: 'agent_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'toAgent', algorithm: 'btree', columns: [
        'toAgent',
      ] },
    ],
    constraints: [
      { name: 'agent_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentMessageRow),
  album: __table({
    name: 'album',
    indexes: [
      { name: 'handle', algorithm: 'btree', columns: [
        'handle',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'album_handle_key', constraint: 'unique', columns: ['handle'] },
      { name: 'album_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AlbumRow),
  album_image: __table({
    name: 'album_image',
    indexes: [
      { name: 'albumId', algorithm: 'btree', columns: [
        'albumId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'imageId', algorithm: 'btree', columns: [
        'imageId',
      ] },
    ],
    constraints: [
      { name: 'album_image_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AlbumImageRow),
  app: __table({
    name: 'app',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'ownerIdentity', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
      { name: 'slug', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'app_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'app_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, AppRow),
  app_message: __table({
    name: 'app_message',
    indexes: [
      { name: 'appId', algorithm: 'btree', columns: [
        'appId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'app_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AppMessageRow),
  app_version: __table({
    name: 'app_version',
    indexes: [
      { name: 'appId', algorithm: 'btree', columns: [
        'appId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'app_version_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AppVersionRow),
  code_session: __table({
    name: 'code_session',
    indexes: [
      { name: 'codeSpace', algorithm: 'btree', columns: [
        'codeSpace',
      ] },
    ],
    constraints: [
      { name: 'code_session_code_space_key', constraint: 'unique', columns: ['codeSpace'] },
    ],
  }, CodeSessionRow),
  credits: __table({
    name: 'credits',
    indexes: [
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'credits_user_identity_key', constraint: 'unique', columns: ['userIdentity'] },
    ],
  }, CreditsRow),
  direct_message: __table({
    name: 'direct_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'toIdentity', algorithm: 'btree', columns: [
        'toIdentity',
      ] },
    ],
    constraints: [
      { name: 'direct_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DirectMessageRow),
  enhancement_job: __table({
    name: 'enhancement_job',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'imageId', algorithm: 'btree', columns: [
        'imageId',
      ] },
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'enhancement_job_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnhancementJobRow),
  generation_job: __table({
    name: 'generation_job',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'generation_job_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GenerationJobRow),
  health_check: __table({
    name: 'health_check',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'health_check_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HealthCheckRow),
  image: __table({
    name: 'image',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'image_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ImageRow),
  mcp_task: __table({
    name: 'mcp_task',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'mcp_task_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, McpTaskRow),
  oauth_link: __table({
    name: 'oauth_link',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'oauth_link_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OauthLinkRow),
  page: __table({
    name: 'page',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'slug', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'page_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'page_slug_key', constraint: 'unique', columns: ['slug'] },
    ],
  }, PageRow),
  page_block: __table({
    name: 'page_block',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'pageId', algorithm: 'btree', columns: [
        'pageId',
      ] },
    ],
    constraints: [
      { name: 'page_block_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PageBlockRow),
  pipeline: __table({
    name: 'pipeline',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pipeline_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PipelineRow),
  platform_event: __table({
    name: 'platform_event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'platform_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlatformEventRow),
  registered_tool: __table({
    name: 'registered_tool',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
      { name: 'providerIdentity', algorithm: 'btree', columns: [
        'providerIdentity',
      ] },
    ],
    constraints: [
      { name: 'registered_tool_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RegisteredToolRow),
  subject: __table({
    name: 'subject',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'imageId', algorithm: 'btree', columns: [
        'imageId',
      ] },
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'subject_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SubjectRow),
  tool_usage: __table({
    name: 'tool_usage',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'toolName', algorithm: 'btree', columns: [
        'toolName',
      ] },
    ],
    constraints: [
      { name: 'tool_usage_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ToolUsageRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'handle', algorithm: 'btree', columns: [
        'handle',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_handle_key', constraint: 'unique', columns: ['handle'] },
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  user_tool_preference: __table({
    name: 'user_tool_preference',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'userIdentity', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'user_tool_preference_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserToolPreferenceRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("album_create", AlbumCreateReducer),
  __reducerSchema("album_delete", AlbumDeleteReducer),
  __reducerSchema("album_image_add", AlbumImageAddReducer),
  __reducerSchema("album_image_remove", AlbumImageRemoveReducer),
  __reducerSchema("album_update", AlbumUpdateReducer),
  __reducerSchema("claim_mcp_task", ClaimMcpTaskReducer),
  __reducerSchema("complete_mcp_task", CompleteMcpTaskReducer),
  __reducerSchema("create_app", CreateAppReducer),
  __reducerSchema("create_app_version", CreateAppVersionReducer),
  __reducerSchema("create_page", CreatePageReducer),
  __reducerSchema("create_page_block", CreatePageBlockReducer),
  __reducerSchema("credits_add", CreditsAddReducer),
  __reducerSchema("credits_consume", CreditsConsumeReducer),
  __reducerSchema("delete_app", DeleteAppReducer),
  __reducerSchema("delete_page", DeletePageReducer),
  __reducerSchema("delete_page_block", DeletePageBlockReducer),
  __reducerSchema("enhancement_job_create", EnhancementJobCreateReducer),
  __reducerSchema("enhancement_job_update", EnhancementJobUpdateReducer),
  __reducerSchema("generation_job_create", GenerationJobCreateReducer),
  __reducerSchema("generation_job_update", GenerationJobUpdateReducer),
  __reducerSchema("image_create", ImageCreateReducer),
  __reducerSchema("image_delete", ImageDeleteReducer),
  __reducerSchema("image_update", ImageUpdateReducer),
  __reducerSchema("invoke_tool_request", InvokeToolRequestReducer),
  __reducerSchema("link_oauth", LinkOauthReducer),
  __reducerSchema("mark_agent_message_delivered", MarkAgentMessageDeliveredReducer),
  __reducerSchema("mark_dm_read", MarkDmReadReducer),
  __reducerSchema("pipeline_create", PipelineCreateReducer),
  __reducerSchema("pipeline_delete", PipelineDeleteReducer),
  __reducerSchema("pipeline_update", PipelineUpdateReducer),
  __reducerSchema("record_health_check", RecordHealthCheckReducer),
  __reducerSchema("record_platform_event", RecordPlatformEventReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("register_tool", RegisterToolReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("reorder_page_blocks", ReorderPageBlocksReducer),
  __reducerSchema("restore_app", RestoreAppReducer),
  __reducerSchema("send_agent_message", SendAgentMessageReducer),
  __reducerSchema("send_app_message", SendAppMessageReducer),
  __reducerSchema("send_dm", SendDmReducer),
  __reducerSchema("subject_create", SubjectCreateReducer),
  __reducerSchema("subject_delete", SubjectDeleteReducer),
  __reducerSchema("unregister_agent", UnregisterAgentReducer),
  __reducerSchema("unregister_tool", UnregisterToolReducer),
  __reducerSchema("update_app", UpdateAppReducer),
  __reducerSchema("update_app_status", UpdateAppStatusReducer),
  __reducerSchema("update_code_session", UpdateCodeSessionReducer),
  __reducerSchema("update_page", UpdatePageReducer),
  __reducerSchema("update_page_block", UpdatePageBlockReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

