// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  userIdentity: __t.option(__t.identity()).name("user_identity"),
  name: __t.string(),
  description: __t.option(__t.string()),
  visibility: __t.string(),
  shareToken: __t.option(__t.string()).name("share_token"),
  tier: __t.string(),
  analysisConfigJson: __t.option(__t.string()).name("analysis_config_json"),
  autoCropConfigJson: __t.option(__t.string()).name("auto_crop_config_json"),
  promptConfigJson: __t.option(__t.string()).name("prompt_config_json"),
  generationConfigJson: __t.option(__t.string()).name("generation_config_json"),
  usageCount: __t.u64().name("usage_count"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
