// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.option(__t.string()),
  description: __t.option(__t.string()),
  visibility: __t.option(__t.string()),
  tier: __t.option(__t.string()),
  analysisConfigJson: __t.option(__t.string()),
  autoCropConfigJson: __t.option(__t.string()),
  promptConfigJson: __t.option(__t.string()),
  generationConfigJson: __t.option(__t.string()),
  shareToken: __t.option(__t.string()),
};
