// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  identity: __t.identity(),
  displayName: __t.string(),
  capabilities: __t.array(__t.string()),
  online: __t.bool(),
  lastSeen: __t.u64(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentMessage = __t.object("AgentMessage", {
  id: __t.u64(),
  fromAgent: __t.identity(),
  toAgent: __t.identity(),
  content: __t.string(),
  timestamp: __t.u64(),
  delivered: __t.bool(),
});
export type AgentMessage = __Infer<typeof AgentMessage>;

export const Album = __t.object("Album", {
  id: __t.u64(),
  handle: __t.string(),
  userIdentity: __t.identity(),
  name: __t.string(),
  description: __t.option(__t.string()),
  coverImageId: __t.option(__t.string()),
  privacy: __t.string(),
  defaultTier: __t.string(),
  shareToken: __t.option(__t.string()),
  sortOrder: __t.u32(),
  pipelineId: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Album = __Infer<typeof Album>;

export const AlbumImage = __t.object("AlbumImage", {
  id: __t.u64(),
  albumId: __t.u64(),
  imageId: __t.string(),
  sortOrder: __t.u32(),
  addedAt: __t.u64(),
});
export type AlbumImage = __Infer<typeof AlbumImage>;

export const App = __t.object("App", {
  id: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  description: __t.string(),
  ownerIdentity: __t.identity(),
  status: __t.string(),
  r2CodeKey: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type App = __Infer<typeof App>;

export const AppMessage = __t.object("AppMessage", {
  id: __t.u64(),
  appId: __t.u64(),
  role: __t.string(),
  content: __t.string(),
  createdAt: __t.u64(),
});
export type AppMessage = __Infer<typeof AppMessage>;

export const AppVersion = __t.object("AppVersion", {
  id: __t.u64(),
  appId: __t.u64(),
  version: __t.u32(),
  codeHash: __t.string(),
  changeDescription: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.u64(),
});
export type AppVersion = __Infer<typeof AppVersion>;

export const CodeSession = __t.object("CodeSession", {
  codeSpace: __t.string(),
  code: __t.string(),
  html: __t.string(),
  css: __t.string(),
  transpiled: __t.string(),
  messagesJson: __t.string(),
  lastUpdatedBy: __t.identity(),
  updatedAt: __t.u64(),
});
export type CodeSession = __Infer<typeof CodeSession>;

export const Credits = __t.object("Credits", {
  userIdentity: __t.identity(),
  balance: __t.i64(),
  updatedAt: __t.u64(),
});
export type Credits = __Infer<typeof Credits>;

export const DirectMessage = __t.object("DirectMessage", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  content: __t.string(),
  readStatus: __t.bool(),
  createdAt: __t.u64(),
});
export type DirectMessage = __Infer<typeof DirectMessage>;

export const EnhancementJob = __t.object("EnhancementJob", {
  id: __t.string(),
  imageId: __t.string(),
  userIdentity: __t.identity(),
  tier: __t.string(),
  creditsCost: __t.u32(),
  status: __t.string(),
  enhancedUrl: __t.option(__t.string()),
  enhancedR2Key: __t.option(__t.string()),
  enhancedWidth: __t.option(__t.u32()),
  enhancedHeight: __t.option(__t.u32()),
  enhancedSizeBytes: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  retryCount: __t.u32(),
  metadataJson: __t.option(__t.string()),
  processingStartedAt: __t.option(__t.u64()),
  processingCompletedAt: __t.option(__t.u64()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type EnhancementJob = __Infer<typeof EnhancementJob>;

export const GenerationJob = __t.object("GenerationJob", {
  id: __t.string(),
  userIdentity: __t.identity(),
  jobType: __t.string(),
  tier: __t.string(),
  creditsCost: __t.u32(),
  status: __t.string(),
  prompt: __t.string(),
  inputImageUrl: __t.option(__t.string()),
  outputImageUrl: __t.option(__t.string()),
  outputWidth: __t.option(__t.u32()),
  outputHeight: __t.option(__t.u32()),
  outputSizeBytes: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type GenerationJob = __Infer<typeof GenerationJob>;

export const HealthCheck = __t.object("HealthCheck", {
  id: __t.u64(),
  service: __t.string(),
  status: __t.string(),
  latencyMs: __t.u32(),
  checkedAt: __t.u64(),
});
export type HealthCheck = __Infer<typeof HealthCheck>;

export const Image = __t.object("Image", {
  id: __t.string(),
  userIdentity: __t.identity(),
  name: __t.string(),
  description: __t.option(__t.string()),
  originalUrl: __t.string(),
  originalR2Key: __t.string(),
  originalWidth: __t.u32(),
  originalHeight: __t.u32(),
  originalSizeBytes: __t.u64(),
  originalFormat: __t.string(),
  isPublic: __t.bool(),
  viewCount: __t.u64(),
  tags: __t.array(__t.string()),
  shareToken: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Image = __Infer<typeof Image>;

export const McpTask = __t.object("McpTask", {
  id: __t.u64(),
  toolName: __t.string(),
  argumentsJson: __t.string(),
  requesterIdentity: __t.identity(),
  providerIdentity: __t.option(__t.identity()),
  status: __t.string(),
  resultJson: __t.option(__t.string()),
  error: __t.option(__t.string()),
  createdAt: __t.u64(),
  completedAt: __t.option(__t.u64()),
});
export type McpTask = __Infer<typeof McpTask>;

export const OauthLink = __t.object("OauthLink", {
  id: __t.u64(),
  userIdentity: __t.identity(),
  provider: __t.string(),
  providerAccountId: __t.string(),
  createdAt: __t.u64(),
});
export type OauthLink = __Infer<typeof OauthLink>;

export const Page = __t.object("Page", {
  id: __t.u64(),
  slug: __t.string(),
  title: __t.string(),
  description: __t.string(),
  published: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Page = __Infer<typeof Page>;

export const PageBlock = __t.object("PageBlock", {
  id: __t.u64(),
  pageId: __t.u64(),
  blockType: __t.string(),
  contentJson: __t.string(),
  sortOrder: __t.u32(),
});
export type PageBlock = __Infer<typeof PageBlock>;

export const Pipeline = __t.object("Pipeline", {
  id: __t.string(),
  userIdentity: __t.option(__t.identity()),
  name: __t.string(),
  description: __t.option(__t.string()),
  visibility: __t.string(),
  shareToken: __t.option(__t.string()),
  tier: __t.string(),
  analysisConfigJson: __t.option(__t.string()),
  autoCropConfigJson: __t.option(__t.string()),
  promptConfigJson: __t.option(__t.string()),
  generationConfigJson: __t.option(__t.string()),
  usageCount: __t.u64(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Pipeline = __Infer<typeof Pipeline>;

export const PlatformEvent = __t.object("PlatformEvent", {
  id: __t.u64(),
  source: __t.string(),
  eventType: __t.string(),
  metadataJson: __t.string(),
  userIdentity: __t.option(__t.identity()),
  timestamp: __t.u64(),
});
export type PlatformEvent = __Infer<typeof PlatformEvent>;

export const RegisteredTool = __t.object("RegisteredTool", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  inputSchema: __t.string(),
  providerIdentity: __t.identity(),
  category: __t.string(),
  createdAt: __t.u64(),
});
export type RegisteredTool = __Infer<typeof RegisteredTool>;

export const Subject = __t.object("Subject", {
  id: __t.u64(),
  userIdentity: __t.identity(),
  imageId: __t.string(),
  label: __t.string(),
  subjectType: __t.string(),
  description: __t.option(__t.string()),
  createdAt: __t.u64(),
});
export type Subject = __Infer<typeof Subject>;

export const ToolUsage = __t.object("ToolUsage", {
  id: __t.u64(),
  toolName: __t.string(),
  userIdentity: __t.identity(),
  timestamp: __t.u64(),
  durationMs: __t.u32(),
  success: __t.bool(),
});
export type ToolUsage = __Infer<typeof ToolUsage>;

export const User = __t.object("User", {
  identity: __t.identity(),
  handle: __t.string(),
  displayName: __t.string(),
  email: __t.string(),
  role: __t.string(),
  avatarUrl: __t.string(),
  online: __t.bool(),
  lastSeen: __t.u64(),
  createdAt: __t.u64(),
});
export type User = __Infer<typeof User>;

export const UserToolPreference = __t.object("UserToolPreference", {
  id: __t.u64(),
  userIdentity: __t.identity(),
  toolName: __t.string(),
  enabled: __t.bool(),
  customConfig: __t.string(),
});
export type UserToolPreference = __Infer<typeof UserToolPreference>;

